steps:
  # Build and deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gmail-scraper'
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'claude-service-account@claude-mcp-457317.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'PROJECT_ID=claude-mcp-457317,DATASET_ID=gmail_analytics,TABLE_ID=messages,ADMIN_EMAIL=avi@envsn.com'
      - '--timeout'
      - '3600'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '1'

options:
  logging: CLOUD_LOGGING_ONLY
