steps:
  # Step 1: Build and deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gmail-scraper'
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'claude-service-account@claude-mcp-457317.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'PROJECT_ID=claude-mcp-457317,DATASET_ID=gmail_analytics,TABLE_ID=messages,ADMIN_EMAIL=avi@envsn.com'
      - '--timeout'
      - '3600'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '1'

  # Step 2: Delete existing scheduler job (if exists)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'delete-old-scheduler'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud scheduler jobs delete gmail-scraper-5min \
          --location=us-central1 \
          --quiet 2>/dev/null || echo "No existing job to delete"

  # Step 3: Create 5-minute scheduler job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'create-scheduler'
    entrypoint: bash
    args:
      - '-c'
      - |
        SERVICE_URL=$(gcloud run services describe gmail-scraper \
          --region=us-central1 \
          --format='value(status.url)')

        gcloud scheduler jobs create http gmail-scraper-5min \
          --location=us-central1 \
          --schedule="*/5 * * * *" \
          --time-zone="America/New_York" \
          --uri="$${SERVICE_URL}/" \
          --http-method=POST \
          --headers="Content-Type=application/json" \
          --message-body='{"incremental": true, "max_per_user": 100}' \
          --attempt-deadline=3600s \
          --description="5-minute incremental Gmail scrape to BigQuery"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: gmail-scraper
